function initMobileMenu(){const btnMobile=document.getElementById('btn-mobile');const navMenu=document.getElementById('menu-principal');if(!btnMobile||!navMenu)return;const toggleMenu=(event)=>{if(event.type==='touchstart')event.preventDefault();const body=document.body;const isMenuActive=navMenu.classList.contains('active');btnMobile.classList.toggle('active',!isMenuActive);navMenu.classList.toggle('active',!isMenuActive);body.classList.toggle('menu-open',!isMenuActive);btnMobile.setAttribute('aria-expanded',!isMenuActive);btnMobile.setAttribute('aria-label',!isMenuActive?'Fechar menu':'Abrir menu')};btnMobile.addEventListener('click',toggleMenu);btnMobile.addEventListener('touchstart',toggleMenu)}
function initChatbot(){const chatbotToggleBtn=document.getElementById('chatbot-toggle-btn');const chatbotWindow=document.getElementById('chatbot-window');const chatbotCloseBtn=document.getElementById('chatbot-close-btn');const chatbotMessages=document.getElementById('chatbot-messages');const chatbotInput=document.getElementById('chatbot-input');const chatbotSendBtn=document.getElementById('chatbot-send-btn');if(!chatbotToggleBtn||!chatbotWindow||!chatbotCloseBtn)return;chatbotToggleBtn.addEventListener('click',()=>{chatbotWindow.classList.remove('hidden');chatbotToggleBtn.classList.add('hidden')});chatbotCloseBtn.addEventListener('click',()=>{chatbotWindow.classList.add('hidden');chatbotToggleBtn.classList.remove('hidden')});if(!chatbotSendBtn||!chatbotInput||!chatbotMessages)return;const addMessage=(text,sender)=>{const messageElement=document.createElement('div');messageElement.classList.add('chat-message',`${sender}-message`);messageElement.textContent=text;chatbotMessages.appendChild(messageElement);chatbotMessages.scrollTop=chatbotMessages.scrollHeight};const getBotResponse=(userText)=>{const text=userText.toLowerCase().trim();let botResponse="";switch(text){case '1':botResponse="Nossos principais projetos são: Escola da Autonomia, Rede de Acolhimento e Abrigos Seguros. Você pode saber mais na nossa página de Projetos.";break;case '2':botResponse="Ficamos felizes com seu interesse! Você pode se cadastrar como voluntária na página Quero Ajudar'. O link está no menu principal do site.";break;case '3':botResponse="Para ajuda imediata, ligue para 180 (Central de Atendimento à Mulher). Para falar conosco, envie um e-mail para: contato@mulheresfortes.org.br ou ligue para (11) 98765-4321.";break;default:if(text.includes('projeto')){botResponse="Nossos principais projetos são: Escola da Autonomia, Rede de Acolhimento e Abrigos Seguros. Você pode saber mais na nossa página de Projetos."}else if(text.includes('voluntari')||text.includes('ajudar')){botResponse="Ficamos felizes com seu interesse! Você pode se cadastrar como voluntária na página 'Quero Ajudar'. O link está no menu principal do site."}else if(text.includes('ajuda')||text.includes('contato')||text.includes('urgente')){botResponse="Para ajuda imediata, ligue para 180 (Central de Atendimento à Mulher). Para falar conosco, envie um e-mail para contato@mulheresfortes.org.br ou ligue para (11) 98765-4321."}else{botResponse="Desculpe, não entendi. Por favor, escolha uma das opções do menu ou reformule sua pergunta. Se esta for uma emergência, ligue para 180."}}
addMessage(botResponse,'bot')};const handleSend=()=>{const userText=chatbotInput.value.trim();if(userText){addMessage(userText,'user');chatbotInput.value='';setTimeout(()=>{getBotResponse(userText)},1000)}};chatbotSendBtn.addEventListener('click',handleSend);chatbotInput.addEventListener('keypress',(e)=>{if(e.key==='Enter'){handleSend()}});const showMenu=()=>{const menuText=`Como posso ajudar hoje?
1. Saber mais sobre os projetos;
2. Como ser voluntário(a);
3. Contatos e ajuda urgente.`;addMessage(menuText,'bot')};setTimeout(()=>{addMessage("Olá! Sou a assistente virtual da Mulheres + Fortes.",'bot');setTimeout(showMenu,500)},500)}
function initPixCopy(){const showPixBtn=document.getElementById("show-pix-key-btn");const pixDetails=document.getElementById("pix-key-details");const copyPixBtn=document.getElementById("copy-pix-btn");const pixKeyInput=document.getElementById("pix-key");const copyFeedback=document.getElementById("copy-feedback");if(!showPixBtn||!pixDetails)return;showPixBtn.addEventListener("click",()=>{pixDetails.hidden=!pixDetails.hidden});if(copyPixBtn&&pixKeyInput&&copyFeedback){copyPixBtn.addEventListener("click",()=>{navigator.clipboard.writeText(pixKeyInput.value).then(()=>{copyFeedback.hidden=!1;setTimeout(()=>{copyFeedback.hidden=!0},2000)}).catch(err=>{console.error("Falha ao copiar a chave PIX: ",err)})})}}
function initForm(){const form=document.getElementById('cadastro-form');const successMessage=document.getElementById('success-message');if(!form||!successMessage)return;const cpfInput=document.getElementById('cpf');const telefoneInput=document.getElementById('telefone');const cepInput=document.getElementById('cep');if(cpfInput){cpfInput.addEventListener('input',(e)=>{let value=e.target.value.replace(/\D/g,'');value=value.replace(/(\d{3})(\d)/,'$1.$2');value=value.replace(/(\d{3})(\d)/,'$1.$2');value=value.replace(/(\d{3})(\d{1,2})$/,'$1-$2');e.target.value=value})}
if(telefoneInput){telefoneInput.addEventListener('input',(e)=>{let value=e.target.value.replace(/\D/g,'');value=value.replace(/^(\d{2})(\d)/g,'($1) $2');if(value.length>13){value=value.replace(/(\d{5})(\d)/,'$1-$2')}else{value=value.replace(/(\d{4})(\d)/,'$1-$2')}
if(value.length===14&&e.inputType==='deleteContentBackward'){value=value.replace('-','')}
e.target.value=value})}
if(cepInput){cepInput.addEventListener('input',(e)=>{let value=e.target.value.replace(/\D/g,'');value=value.replace(/^(\d{5})(\d)/,'$1-$2');e.target.value=value})}
form.addEventListener('submit',(event)=>{event.preventDefault();if(form.checkValidity()){form.style.display='none';successMessage.hidden=!1;successMessage.style.display='block';successMessage.scrollIntoView({behavior:'smooth'})}else{console.log("Formulário inválido. Por favor, corrija os campos marcados.")}})}
function initThemeSwitcher(){const darkThemeBtn=document.getElementById('theme-toggle-dark');const body=document.body;if(!darkThemeBtn)return;const applyTheme=(theme)=>{body.classList.remove('dark-mode');if(theme==='dark-mode'){body.classList.add(theme);darkThemeBtn.classList.add('active');darkThemeBtn.setAttribute('aria-label','Ativar modo claro')}else{darkThemeBtn.classList.remove('active');darkThemeBtn.setAttribute('aria-label','Ativar modo escuro')}
localStorage.setItem('theme',theme||'light')};const savedTheme=localStorage.getItem('theme');const validTheme=savedTheme==='dark-mode'?'dark-mode':'light';applyTheme(validTheme);darkThemeBtn.addEventListener('click',()=>{if(body.classList.contains('dark-mode')){applyTheme(null)}else{applyTheme('dark-mode')}})}
document.addEventListener('DOMContentLoaded',()=>{initMobileMenu();initChatbot();initForm();initPixCopy();initThemeSwitcher()})